/* eslint-disable global-require */
export const Images = {
  logo: require('../assets/images/app-icon.png'),
  aries: require('../assets/images/star-signs/aries.png'),
  taurus: require('../assets/images/star-signs/taurus.png'),
  gemini: require('../assets/images/star-signs/gemini.png'),
  cancer: require('../assets/images/star-signs/cancer.png'),
  leo: require('../assets/images/star-signs/leo.png'),
  virgo: require('../assets/images/star-signs/virgo.png'),
  libra: require('../assets/images/star-signs/libra.png'),
  scorpio: require('../assets/images/star-signs/scorpio.png'),
  sagittarius: require('../assets/images/star-signs/sagittarius.png'),
  capricorn: require('../assets/images/star-signs/capricorn.png'),
  aquarius: require('../assets/images/star-signs/aquarius.png'),
  pisces: require('../assets/images/star-signs/pisces.png'),
  'aries-sign': require('../assets/images/star-signs/aries-sign.png'),
  'taurus-sign': require('../assets/images/star-signs/taurus-sign.png'),
  'gemini-sign': require('../assets/images/star-signs/gemini-sign.png'),
  'cancer-sign': require('../assets/images/star-signs/cancer-sign.png'),
  'leo-sign': require('../assets/images/star-signs/leo-sign.png'),
  'virgo-sign': require('../assets/images/star-signs/virgo-sign.png'),
  'libra-sign': require('../assets/images/star-signs/libra-sign.png'),
  'scorpio-sign': require('../assets/images/star-signs/scorpio-sign.png'),
  'sagittarius-sign': require('../assets/images/star-signs/sagittarius-sign.png'),
  'capricorn-sign': require('../assets/images/star-signs/capricorn-sign.png'),
  'aquarius-sign': require('../assets/images/star-signs/aquarius-sign.png'),
  'pisces-sign': require('../assets/images/star-signs/pisces-sign.png'),
};

export const LocalCachedImages = [Images.logo];
